import StyleDictionary from 'style-dictionary';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, basename } from 'node:path';
import fs from 'node:fs/promises';

const __dirname = dirname(fileURLToPath(import.meta.url));
const tokensDir = resolve(__dirname, 'src/tokens');

const allSources = [
  'palette.json',
  'signature.light.json',
  'signature.dark.json',
  'semantic.light.json',
  'semantic.dark.json',
  'legacy.light.json',
  'legacy.dark.json',
  'dimension.json',
  'shadow.json',
  'typography.json',
  'heading.json',
  'motion.json',
  'z-index.json',
].map(f => resolve(tokensDir, f));

const lightSources = allSources.filter(p => !basename(p).includes('.dark.'));
const darkSourceBasenames = new Set(['signature.dark.json', 'semantic.dark.json', 'legacy.dark.json']);

/**
 * Custom CSS format: emit a single selector block with --kebab-case-name: value;
 * pairs. Token names are derived from the JSON path joined by hyphens. References
 * are preserved as var(--name) so the cascade resolves them at runtime.
 */
StyleDictionary.registerFormat({
  name: 'campfire/css-block',
  format: async ({ dictionary, options }) => {
    const selector = options.selector ?? ':root';
    const tokenFilter = options.tokenFilter ?? (() => true);
    const tokens = dictionary.allTokens
      .filter(tokenFilter)
      .map(t => {
        const name = t.path.join('-');
        const value = formatValue(t, dictionary);
        return `  --${name}: ${value};`;
      });
    return `${selector} {\n${tokens.join('\n')}\n}\n`;
  },
});

/**
 * Custom JS format: emit the full token tree as an ES module default export,
 * matching the shape of tokens.json. Consumers get
 * `import tokens from '@jeremyfuksa/campfire/tokens'`
 * and can access `tokens.primary['500'].$value` etc.
 */
StyleDictionary.registerFormat({
  name: 'campfire/js-tree',
  format: ({ dictionary }) => {
    const tree = {};
    for (const token of dictionary.allTokens) {
      let cursor = tree;
      for (let i = 0; i < token.path.length - 1; i++) {
        const key = token.path[i];
        cursor[key] ??= {};
        cursor = cursor[key];
      }
      cursor[token.path[token.path.length - 1]] = {
        $value: token.$value ?? token.value,
        $type: token.$type ?? token.type,
      };
    }
    return `/** Auto-generated by Style Dictionary. */\nconst tokens = ${JSON.stringify(tree, null, 2)};\nexport default tokens;\n`;
  },
});

/**
 * Custom JSON format: emit the full token tree in W3C DTCG shape,
 * preserving $value and $type per leaf. Default `json/nested` flattens
 * leaves to bare values, which loses DTCG semantics.
 */
StyleDictionary.registerFormat({
  name: 'campfire/json-dtcg',
  format: ({ dictionary, options }) => {
    const filter = options?.tokenFilter ?? (() => true);
    const tree = {};
    for (const token of dictionary.allTokens) {
      if (!filter(token)) continue;
      let cursor = tree;
      for (let i = 0; i < token.path.length - 1; i++) {
        const key = token.path[i];
        cursor[key] ??= {};
        cursor = cursor[key];
      }
      cursor[token.path[token.path.length - 1]] = {
        $value: token.$value ?? token.value,
        $type: token.$type ?? token.type,
      };
    }
    return JSON.stringify(tree, null, 2) + '\n';
  },
});

StyleDictionary.registerFormat({
  name: 'campfire/dts-tree',
  format: () => {
    return `/** Auto-generated by Style Dictionary. */\ndeclare const tokens: Record<string, unknown>;\nexport default tokens;\n`;
  },
});

function formatValue(token, dictionary) {
  // If the original raw value is a reference like "{primary.500}",
  // emit it as var(--primary-500) so cascade resolves at runtime.
  const raw = token.original.$value ?? token.original.value;
  if (typeof raw === 'string' && raw.includes('{') && raw.includes('}')) {
    return raw.replace(/\{([^}]+)\}/g, (_, ref) => {
      const refName = ref.split('.').join('-');
      return `var(--${refName})`;
    });
  }
  return token.$value ?? token.value;
}

async function buildLight() {
  const sd = new StyleDictionary({
    source: lightSources,
    log: { warnings: 'disabled', verbosity: 'silent' },
    platforms: {
      css: {
        buildPath: 'src/styles/',
        files: [{
          destination: '_tokens.light.css',
          format: 'campfire/css-block',
          options: { selector: ':root' },
        }],
      },
      json: {
        buildPath: 'dist/',
        transformGroup: 'js',
        files: [{
          destination: 'tokens.json',
          format: 'campfire/json-dtcg',
        }],
      },
      js: {
        buildPath: 'dist/',
        transformGroup: 'js',
        files: [
          { destination: 'tokens.js', format: 'campfire/js-tree' },
          { destination: 'tokens.d.ts', format: 'campfire/dts-tree' },
        ],
      },
    },
  });
  await sd.hasInitialized;
  await sd.buildAllPlatforms();
}

async function buildDark() {
  const sd = new StyleDictionary({
    source: allSources, // need full graph so refs resolve
    log: { warnings: 'disabled', verbosity: 'silent' },
    platforms: {
      css: {
        buildPath: 'src/styles/',
        files: [{
          destination: '_tokens.dark.css',
          format: 'campfire/css-block',
          options: {
            selector: '.dark',
            // emit only tokens whose source file is one of the dark overrides
            tokenFilter: (token) => darkSourceBasenames.has(basename(token.filePath)),
          },
        }],
      },
      json: {
        buildPath: 'dist/',
        transformGroup: 'js',
        files: [{
          destination: 'tokens.dark.json',
          format: 'campfire/json-dtcg',
          options: {
            tokenFilter: (token) => darkSourceBasenames.has(basename(token.filePath)),
          },
        }],
      },
    },
  });
  await sd.hasInitialized;
  await sd.buildAllPlatforms();
}

async function concatenate() {
  const light = await fs.readFile(resolve(__dirname, 'src/styles/_tokens.light.css'), 'utf8');
  const dark = await fs.readFile(resolve(__dirname, 'src/styles/_tokens.dark.css'), 'utf8');
  const header = `/* AUTOGENERATED by style-dictionary.config.mjs — do not edit by hand. */\n/* Source: src/tokens/*.json */\n\n`;
  const out = header + light + '\n' + dark;
  await fs.writeFile(resolve(__dirname, 'src/styles/tokens.generated.css'), out);
  await fs.mkdir(resolve(__dirname, 'dist'), { recursive: true });
  await fs.writeFile(resolve(__dirname, 'dist/tokens.css'), out);
  await fs.unlink(resolve(__dirname, 'src/styles/_tokens.light.css'));
  await fs.unlink(resolve(__dirname, 'src/styles/_tokens.dark.css'));
}

await buildLight();
await buildDark();
await concatenate();
console.log('✓ tokens built: src/styles/tokens.generated.css, dist/tokens.{json,js,d.ts}, dist/tokens.dark.json');
